### ISSUE TITLE
Doesn't load on Bitwig Linux

### ISSUE THREAD

**Issue by SilverLPs** [publicsamples/Quetzalcoatl#26]
Doesn't load on Bitwig 5.1.9 with Kubuntu 24.04 but it DOES work correctly with REAPER or Carlas Standalone. Interestingly, it also doesn't load with the Plugin Version of Carla, when Carla is loaded in Bitwig.

Bitwig reports the following in CLI:
        com.bitwig.base.io.ekG: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Unknown file type for file /home/adl_silver/.vst3/Modular Samples Quetzalcoatl
        at KyH.ysk(SourceFile:40)
        at KyH.CgR(SourceFile:14)
        at eVS.ZxU(SourceFile:401)
        at YRE.run(SourceFile:88)
        at dMw.run(SourceFile:307)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Unknown file type for file /home/adl_silver/.vst3/Modular Samples Quetzalcoatl
        at com.bitwig.flt.library.metadata.reader.TRi.cbA(SourceFile:58)
        at com.bitwig.flt.library.metadata.reader.aQH.ysk(SourceFile:44)
        at com.bitwig.flt.library.metadata.reader.aQH.cbA(SourceFile:20)
        at com.bitwig.flt.library.metadata.reader.dXV.cbA(SourceFile:22)
        at KyH.ysk(SourceFile:36)
        ... 7 more

If loaded into Carlas Plugin Version in Bitwig, Carla will also report, that it can't get metadata from the plugin and refuses to open it, just like Bitwig. So there is no "crash" because it doesn't even open in the first place. However, Bitwig doesn't report any errors when scanning the plugin, it only happens, when Bitwig (or Carla in Bitwig) tries to load the plugin. 

It tried it with an older expanded version I bought (0.6.5) and the newest github version (0.7.1) of the plugin.

**Comment by SilverLPs** [comment]
Oh, and I should add, I have xsettingsd installed, however systemd isn't able to find it. But I dont think my issue is related to the other case, as it does load on REAPER and Carla standalone.

**Comment by SilverLPs** [comment]
UPDATE: Now I loaded the Factory Samplebank and the expansions into it (with Carla) and all of a sudden it does open and work correctly in Bitwig. So it looks like the issue occurs when there is no Samplebank configured in the plugin.

**Comment by cxbignekoc** [comment]
Did you have Pipewire/ Wireplumber/ALSA?

[Can you derive a solution from your problem and its solution for my problem?](https://github.com/publicsamples/Quetzalcoatl/issues/30)

:)

**Comment by SilverLPs** [comment]
@cxbignekoc Kubuntu 24.04 LTS uses Pipewire (which runs ofc on top of ALSA) so that is what I use. However I think that is unrelated to both of our problems. 

You should try to install the Carla Plugin Host from the KXStudio website or alternatively you can use the REAPER (DAW) demo version from their website (do NOT use Flatpak for this). Try to open the plugin with it, if it doesn't work, our problems might be unrelated. If it works, try to load the sound content pack in it. Then close the plugin and the DAW you opened the plugin in and try opening it in Bitwig, for me it worked after a sound content pack was loaded. 

Otherwise if it runs in the Carla Plugin Host, you can also circumvent the problem by loading Carla as a plugin into Bitwig and then load the buggy plugins into Carla (nested plugins), you can also load unsupported plugin types like LV2 into Bitwig this way.

Good luck! 

And btw. if it doesn't work at all, I recommend using a Ubuntu 24.04 based distro (like Kubuntu) as these offer not only the best support for all VST plugins (I managed to get far over 200 plugins to work, both commercially and open source) but they also have working Pipewire support and good kernel settings for low latency. The few adjustments that you need to make on a fresh installation can be found in my kubuntu2404-configs Github repo.

**Comment by RickTaylor79** [comment]
HISE (the framework Q is built on) has received a lot of linux updates this year, including the long standing [XSettings](https://github.com/publicsamples/Quetzalcoatl/issues/11) bug. 

With this in mind, here's v0.8.8 built on the latest dev build of HISE:

https://github.com/publicsamples/Quetzalcoatl/releases/tag/0.8.8

Keep in mind, this is just the standard version for now and the process of updating Q to the latest HISE was not trivial, so some things may not work .

Working on Ubuntu 22 with Reaper and Bitwig here.
